server:
  # Render automatically detects port 10000
  port: ${PORT:8081}

spring:
  application:
    name: user-service
  datasource:
    # Database connection for Railway/Render PostgreSQL
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecoride_user_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:sourabh@2003}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    # Render par dynamic IPs ki wajah se hostname use karna better hai
    prefer-ip-address: false
    # Service ka exact URL taaki Gateway dhoond sake
    hostname: ecoride-deploy-user.onrender.com
    # Render's specific port binding
    non-secure-port: ${server.port}
  client:
    service-url:
      # Aapka live Eureka Server link
      defaultZone: ${EUREKA_SERVER_URL:https://service-registry-qhsy.onrender.com/eureka/}
    register-with-eureka: true
    fetch-registry: true